# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Klor Keyboard"
product_name = "Klor Keyboard"
vendor_id = 0x3a3c # https://github.com/GEIGEIGEIST/qmk-config-klor/blob/main/klor/info.json
product_id = 0x0001
manufacturer = "GEIST"
chip = "rp2040"

[layout]
rows = 8
cols = 6
layers = 1
keymap = [
    [
        ["A", "B", "C", "D", "E", "F"],
        ["G", "H", "I", "J", "K", "L"],
        ["M", "N", "O", "P", "Q", "R"],
        ["S", "T", "U", "V", "W", "X"],

        ["a", "b", "c", "d", "e", "f"],
        ["g", "h", "i", "j", "k", "l"],
        ["m", "n", "o", "p", "q", "r"],
        ["s", "t", "u", "v", "w", "x"],
    ],
]

[split]
connection = "serial"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
serial = [ # TODO(dalero) : Unconfirmed
    { instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" },
]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11"]
output_pins = ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]

# #define MATRIX_ROW_PINS { C6, D7, E6, B4 }
# #define MATRIX_COL_PINS { F6, F7, B1, B3, B2, B6 }

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 4
col_offset = 6
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11"]
output_pins = ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]
