# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Klor Keyboard"
product_name = "Klor Keyboard"
vendor_id = 0x3a3c # https://github.com/GEIGEIGEIST/qmk-config-klor/blob/main/klor/info.json
product_id = 0x0001
manufacturer = "GEIST"
chip = "rp2040"

[matrix]
input_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11"]
output_pins = ["PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13"]

[layout]
rows = 4
cols = 6
layers = 1
keymap = [
    [
        ["__", "Q", "W", "E", "R", "T"],
        ["__", "A", "S", "D", "F", "G"],
        ["__", "Z", "X", "C", "V", "B"],
        ["__", "Escape", "LGui", "Tab", "Space", "__"],
    ],
]

