# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Klor Keyboard"
product_name = "Klor Keyboard"
vendor_id = 0x3a3c # https://github.com/GEIGEIGEIST/qmk-config-klor/blob/main/klor/info.json
product_id = 0x0001
manufacturer = "GEIST"
chip = "rp2040"

[layout]
rows = 8
cols = 6
layers = 1
keymap = [
    [
        ["__", "Q", "W", "E", "R", "T"],
        ["__", "A", "S", "D", "F", "G"],
        ["__", "Z", "X", "C", "V", "B"],
        ["__", "Escape", "LGui", "Tab", "Space", "__"],

        ["Y", "U", "I", "O", "P", "__"],
        ["H", "J", "K", "L", "Semicolon", "__"],
        ["N", "M", "Comma", "Dot", "Backslash", "__"],
        ["__", "Space", "Enter", "Backspace", "Delete", "__"],
    ],
]

[split]
connection = "serial"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
serial = [ 
    { instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" },
]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11"]
output_pins = ["PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13"]

# #define MATRIX_ROW_PINS { C6, D7, E6, B4 }
# #define MATRIX_COL_PINS { F6, F7, B1, B3, B2, B6 }

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 4
col_offset = 0
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_8", "PIN_9", "PIN_10", "PIN_11"]
output_pins = ["PIN_18", "PIN_17", "PIN_16", "PIN_15", "PIN_14", "PIN_13"]
